TRUNCATE purchase_detail;
TRUNCATE purchase_head;
TRUNCATE damage_head;
TRUNCATE damage_detail;
TRUNCATE return_head;
TRUNCATE return_detail;
TRUNCATE purchase_receive_detail;
TRUNCATE purchase_receive_head;
TRUNCATE stock_delivery_detail;
TRUNCATE stock_delivery_head;
TRUNCATE inventory_adjust;
UPDATE product_branch_inventory SET inventory = 0, min_inv = 1, max_inv = 1;