TRUNCATE purchase_detail;
TRUNCATE purchase_head;
TRUNCATE damage_head;
TRUNCATE damage_detail;
TRUNCATE return_head;
TRUNCATE return_detail;
TRUNCATE purchase_receive_detail;
TRUNCATE purchase_receive_head;
TRUNCATE stock_delivery_detail;
TRUNCATE stock_delivery_head;
TRUNCATE inventory_adjust;
TRUNCATE release_head;
TRUNCATE release_detail;
TRUNCATE purchase_return_head;
TRUNCATE purchase_return_detail;
TRUNCATE daily_transaction_summary;
TRUNCATE recent_name;
TRUNCATE release_order_head;
TRUNCATE release_order_detail;
TRUNCATE pickup_summary_head;
TRUNCATE pickup_summary_detail;
TRUNCATE stock_request_head;
TRUNCATE stock_request_detail;
UPDATE user SET `is_first_login` = 0 WHERE `id` <> 1;
UPDATE product_branch_inventory SET inventory = 0, min_inv = 0, max_inv = 0;